"""smarts

Revision ID: 2d328cf798d5
Revises: 2c43599d8881
Create Date: 2025-07-02 05:32:08.060271

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2d328cf798d5"
down_revision: Union[str, Sequence[str], None] = "2c43599d8881"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "smarts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("s", sa.String(), nullable=False),
        sa.Column("m", sa.String(), nullable=False),
        sa.Column("a", sa.String(), nullable=False),
        sa.Column("r", sa.String(), nullable=False),
        sa.Column("t", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_smarts_id"), "smarts", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_smarts_id"), table_name="smarts")
    op.drop_table("smarts")
    # ### end Alembic commands ###
